# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.9
    
# what branches should be evaluated
branches:
    only:
        - main

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8

# a list of commands to run before the main script
before_script:
    - python setup.py install

# the actual commands to run
script:
    - flake8 restaurantrecommender --exit-zero

# generate a coverage report to send to back to user
after_success:
    - coveralls
